@url = https://shiny-space-funicular-j6x5wvx6xpr3vvr-8080.app.github.dev/alunos

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJNYXRyw61jdWxhcyBBUEkiLCJzdWIiOiJhZG1pbiIsImV4cCI6MTc2NDA1NTcwMH0.NUTHZ8moOMzWqgHA-WWiHm4J_wfA_-x7rBUoUcYaP5A

POST {{url}}
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "nome": "Fernanda Rissi",
    "email": "fernanda@gmail.com",
    "telefone": "1488888888",
    "dataMatricula": "2025-11-24"
}

###
GET {{url}}
Authorization:  Bearer {{token}}


###
GET {{url}}/1
Authorization:  Bearer {{token}}


###
PUT {{url}}/1
Content-Type: application/json

{
    "nome": "Erick Cirico Atualizado",
    "dataMatricula": "2025-11-25"
}